UserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: ${self:service}-${self:provider.stage}-userpool
    AutoVerifiedAttributes:
      - email
    Policies:
      PasswordPolicy:
        MinimumLength: 8
        RequireLowercase: true
        RequireNumbers: true
        RequireSymbols: false
        RequireUppercase: true
    Schema:
      - Name: email
        AttributeDataType: String
        Mutable: false
        Required: true
  
UserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    GenerateSecret: false
    UserPoolId:
      Ref: UserPool